### ISSUE TITLE
error after installing

### ISSUE THREAD

**Issue by jianshu93** [AndreLamurias/GraphMB#12]
Dear GraphMB team,

I followed both pip install and conda install guidance but when type grapheme -h, I always have the following error:

Traceback (most recent call last):
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/graphmb/bin/graphmb", line 5, in <module>
    from graphmb.main import main
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/graphmb/lib/python3.7/site-packages/graphmb/__init__.py", line 5, in <module>
    from . import contigsdataset
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/graphmb/lib/python3.7/site-packages/graphmb/contigsdataset.py", line 11, in <module>
    from graphmb.graph_functions import read_reads_mapping_sam, count_kmers, get_kmer_to_id
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/graphmb/lib/python3.7/site-packages/graphmb/graph_functions.py", line 11, in <module>
    from vamb.cluster import cluster as vamb_cluster
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/graphmb/lib/python3.7/site-packages/vamb/__init__.py", line 31, in <module>
    from . import vambtools
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/graphmb/lib/python3.7/site-packages/vamb/vambtools.py", line 8, in <module>
    from vamb._vambtools import _kmercounts, _overwrite_matrix
ImportError: /storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/graphmb/lib/python3.7/site-packages/vamb/_vambtools.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __intel_cpu_feature_indicator

What could be the reason?

THanks,

Jianshu

**Comment by AndreLamurias** [comment]
Hi Jianshu, thanks for the interest!
a quick google led me to this answer: https://github.com/RasmussenLab/vamb/issues/93#issuecomment-954766663
Have you tried that? Otherwise can you try the docker image? Can you run VAMB by itself on your machine?
