### ISSUE TITLE
Marker option in main command

### ISSUE THREAD

**Issue by cyanoluu** [AndreLamurias/GraphMB#21]
Hi,

I would like to ask you for help. I used very basic command to run graphmb:

graphmb --assembly path/to/assembly --outdir dir --assembly_name path/to/assembly --graph_file /path/to/gfa file --depth path/to/depth.txt

I got this error:

logging to met20_graphMB/20230308-132817graphmb_output.log
Running GraphMB 0.2.3
using cuda: False
setting seed to 1
setting tf seed
Reading cache from
Uncaught exception
Traceback (most recent call last):
  File "/home/sehnal/miniconda3/envs/graphmb/bin/graphmb", line 8, in <module>
    sys.exit(main())
  File "/home/sehnal/miniconda3/envs/graphmb/lib/python3.9/site-packages/graphmb/main.py", line 447, in main
    dataset.read_scgs()
  File "/home/sehnal/miniconda3/envs/graphmb/lib/python3.9/site-packages/graphmb/contigsdataset.py", line 560, in read_scgs
    contig_markers = read_contig_genes(scg_path)
  File "/home/sehnal/miniconda3/envs/graphmb/lib/python3.9/site-packages/graphmb/evaluate.py", line 194, in read_contig_genes
    with open(contig_markers, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/sehnal/assembly.fasta/marker_gene_stats.tsv'

I thought that option --marker is optional. I don't have this file and I want to run it without it. Is it possible?

Thank you very much,
Ludek

**Comment by AndreLamurias** [comment]
Hi, for now you can set --markers "" so that no marker file is used. By default GraphMB assumes that there is a marker file so that it is easier to reproduce our results. But we can improve this so that if the file is not found, the user is informed and it runs without that file. Thanks for pointing this out!
