### ISSUE TITLE
KeyError?

### ISSUE THREAD

**Issue by mallen6** [AndreLamurias/GraphMB#24]
Hello, 
I am looking forward to running graphmb and have prepped my input files according to the instructions. 

My install was of graphmb version 0.2.3 using conda:
conda create -n graphmb -c bioconda graphmb  

My command was: 
conda activate graphmb
graphmb --assembly GraphMB_ownDepths/ --outdir GraphMB_ownDepths/graphMB --cuda

It seemed to start running ok but has now given a Key Error? (log copied below). Do you have any suggestions how I can fix this?

Running GraphMB 0.2.3
using cuda: True
setting seed to 1
Cache not found on GraphMB_ownDepths/graphMB
processing sequences GraphMB_ownDepths/assembly.fasta
read 32772 seqs
processing GFA file (edge nodes) GraphMB_ownDepths/assembly_graph.gfa
skipped contigs 4156 < 1000
read 34831, edges
reading depths
reading labels
Saved cache to GraphMB_ownDepths/graphMB

==============Running VAE model=====================
******* Running model: CCVAE **********
***** using edge weights: True ******
***** cluster markers only: False *****
***** self edges only: False *****
***** Using raw kmer+abund features: True
***** SCG neg pairs: (0,)
***** input features dimension: (32772, 104)
Uncaught exception
Traceback (most recent call last):
  File "/srv/scratch/z2194795/miniconda3/envs/graphmb/bin/graphmb", line 10, in <module>
    sys.exit(main())
  File "/srv/scratch/z2194795/miniconda3/envs/graphmb/lib/python3.10/site-packages/graphmb/main.py", line 497, in main
    vae_embs, _ = train_ccvae.run_model_ccvae(dataset, args, logger, 0,
  File "/srv/scratch/z2194795/miniconda3/envs/graphmb/lib/python3.10/site-packages/graphmb/train_ccvae.py", line 170, in run_model_ccvae
    cluster_labels, stats, _, hq_bins = compute_clusters_and_stats(
  File "/srv/scratch/z2194795/miniconda3/envs/graphmb/lib/python3.10/site-packages/graphmb/evaluate.py", line 367, in compute_clusters_and_stats
    unresolved_contigs_with_scgs = np.array([n for i,n in enumerate(node_names) \
  File "/srv/scratch/z2194795/miniconda3/envs/graphmb/lib/python3.10/site-packages/graphmb/evaluate.py", line 368, in <listcomp>
    if labels[i] not in positive_clusters and len(dataset.contig_markers[n]) > 0])
KeyError: 'edge_1'

**Comment by AndreLamurias** [comment]
Hi, sorry for the delay but I think the issue might be with your input data. However can you retry with the latest version (0.2.5) ? it fixes some bugs

**Comment by harrytchild** [comment]
I also get the same error using v0.2.5, so unfortunately this bug doesn't seem to be fixed. Any help would be much appreciated! (see below for log)

Running GraphMB 0.2.5
using cuda: False
setting seed to 1
Cache not found on mag_script_test/bins/QIA_MUTT_4/graphmb_results/
processing sequences mag_script_test/metaflye_assemblies/QIA_MUTT_4/polished.fasta
read 22785 seqs
processing GFA file (edge nodes) mag_script_test/metaflye_assemblies/QIA_MUTT_4/assembly_graph.gfa
skipped contigs 59 < 1000
read 55, edges
reading depths
reading labels
Saved cache to mag_script_test/bins/QIA_MUTT_4/graphmb_results/

Reading assembly info file
==============Running VAE model=====================
******* Running model: CCVAE **********
***** using edge weights: True ******
***** cluster markers only: False *****
***** self edges only: False *****
***** Using raw kmer+abund features: True
***** SCG neg pairs: (0,)
***** input features dimension: (22785, 104)
Uncaught exception
Traceback (most recent call last):
  File "/home/harry/miniconda3/envs/graphmb/bin/graphmb", line 8, in <module>
    sys.exit(main())
  File "/home/harry/miniconda3/envs/graphmb/lib/python3.8/site-packages/graphmb/main.py", line 499, in main
    vae_embs, _, _ = train_ccvae.run_model_ccvae(dataset, args, logger, 0,
  File "/home/harry/miniconda3/envs/graphmb/lib/python3.8/site-packages/graphmb/train_ccvae.py", line 170, in run_model_ccvae
    cluster_labels, stats, _, hq_bins = compute_clusters_and_stats(
  File "/home/harry/miniconda3/envs/graphmb/lib/python3.8/site-packages/graphmb/evaluate.py", line 367, in compute_clusters_and_stats
    unresolved_contigs_with_scgs = np.array([n for i,n in enumerate(node_names) \
  File "/home/harry/miniconda3/envs/graphmb/lib/python3.8/site-packages/graphmb/evaluate.py", line 368, in <listcomp>
    if labels[i] not in positive_clusters and len(dataset.contig_markers[n]) > 0])
KeyError: 'edge_1'

**Comment by harrytchild** [comment]
I have solved this issue, which was a user error. It appears to be caused by inputting an incorrectly formatted --markers file. I was previously generating this using checks on the individual fasta file containing all my contigs, where it requires a file from checkm on all contigs in separate fasta files
