### ISSUE TITLE
data directory missing in 0.2.4 installations

### ISSUE THREAD

**Issue by dpryan79** [AndreLamurias/GraphMB#28]
While updating graphmb in Bioconda to 0.2.4 we're seeing the following error during testing with `python -c "import graphmb"`:

```
21:28:42 BIOCONDA INFO (OUT) Traceback (most recent call last):
21:28:42 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/graphmb_1684876932372/test_tmp/run_test.py", line 2, in <module>
21:28:42 BIOCONDA INFO (OUT)     import graphmb
21:28:42 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/graphmb_1684876932372/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/graphmb/__init__.py", line 2, in <module>
21:28:42 BIOCONDA INFO (OUT)     from . import contigsdataset
21:28:42 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/graphmb_1684876932372/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/graphmb/contigsdataset.py", line 25, in <module>
21:28:42 BIOCONDA INFO (OUT)     BACTERIA_MARKERS = files('graphmb.data').joinpath('Bacteria.ms')
21:28:42 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/graphmb_1684876932372/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/importlib_resources/_common.py", line 46, in wrapper
21:28:42 BIOCONDA INFO (OUT)     return func(anchor)
21:28:42 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/graphmb_1684876932372/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/importlib_resources/_common.py", line 56, in files
21:28:42 BIOCONDA INFO (OUT)     return from_package(resolve(anchor))
21:28:42 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/graphmb_1684876932372/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/functools.py", line 889, in wrapper
21:28:42 BIOCONDA INFO (OUT)     return dispatch(args[0].__class__)(*args, **kw)
21:28:42 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/graphmb_1684876932372/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/importlib_resources/_common.py", line 82, in _
21:28:42 BIOCONDA INFO (OUT)     return importlib.import_module(cand)
21:28:42 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/graphmb_1684876932372/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/importlib/__init__.py", line 126, in import_module
21:28:42 BIOCONDA INFO (OUT)     return _bootstrap._gcd_import(name[level:], package, level)
21:28:42 BIOCONDA INFO (OUT) ModuleNotFoundError: No module named 'graphmb.data'
```

Looking at the setup.py

**Comment by AndreLamurias** [comment]
will be fixed in 0.2.5
